#服务器配置
server:
  port: 8000

spring:
  application:
    name: cms-admin
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/dobi-cms?useSSL=false
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    #修改跳转的前缀和后缀,以下注释部分是spring boot的默认配置
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #开发过程中需将缓存关闭
    cache: false
    check-template: false
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
mybatis:
  mapper-locations: classpath:mapper/*.xml

dobi:
  #文件上传路径
  upload: C:\work\git\dobi-cms\upload\
